### ISSUE TITLE
FileMoveException during tar download 

### ISSUE THREAD

**Issue by alex-weich** [anfema/ion-client-android#177]
During the tar download an FileMoveException occured. 

Observed in the BI Android project. (ION - develop)

Steps to reproduce:
- You need the BI develop branch.
- Live Build
- Start the BI App and try to login in the "Testland" Reise (PW: `IchBinEinTest`)

```
2021-10-11 15:08:20.398 13433-13473/com.anfema.bayerninternational E/FileMoveException: URL: https://bi2020.anfema.com/client/v1/de_DE/testreise/ganz-langer-titel-fur-das-programm-noch-viel-langer-ganz-ganz-lang?variation=default
2021-10-11 15:08:20.399 13433-13433/com.anfema.bayerninternational E/BI Reise: com.anfema.ionclient.exceptions.FileMoveException: Source /data/user/0/com.anfema.bayerninternational/files/testreise/de_DE/default_temp/09d8be270fa82c7395799b5cab7afff8 is a file, which does NOT exist.
    Target /data/user/0/com.anfema.bayerninternational/files/testreise/de_DE/default/09d8be270fa82c7395799b5cab7afff8 is a file, which does  exist.
        at com.anfema.ionclient.utils.FileUtils.move(FileUtils.java:161)
        at com.anfema.ionclient.archive.ArchiveUtils.performUnTar(ArchiveUtils.java:159)
        at com.anfema.ionclient.archive.ArchiveUtils.lambda$unTar$0(ArchiveUtils.java:55)
        at com.anfema.ionclient.archive.-$$Lambda$ArchiveUtils$cPkhTOXV9wVbaLiWWV-98RM7MGo.call(Unknown Source:12)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.call(ObservableFromCallable.java:58)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:55)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.onSuccess(SingleFlatMapObservable.java:109)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
        at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
        at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
        at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2021-10-11 15:08:20.399 13433-13433/com.anfema.bayerninternational E/BI Reise:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by alex-weich** [comment]
I'm able to reproduce this with actual `develop` branch. If have question or not able to reproduce please feel free to write me or call directly.

**Comment by p-fischer** [comment]
I get the same type of error but for another URL: 
https://bi2020.anfema.com/client/v1/de_DE/testreise/test?variation=default

The untaring of the archive only works in the Android ION client if every page file is only included once.
However, the page for https://bi2020.anfema.com/client/v1/de_DE/testreise/test?variation=default is included 3 times in the TAR file. 

Now, the question is, do we need to change the client code to be able to cope with duplicated page files or can this be fixed on backend side?

**Comment by p-fischer** [comment]
The page file of the original error with page identifier `ganz-langer-titel-fur-das-programm-noch-viel-langer-ganz-ganz-lang` is contained twice.

**Comment by p-fischer** [comment]
I could fix this on client side but this should probably also be fixed on backend side.

**Comment by alex-weich** [comment]
BE Issue: https://github.com/anfema/bi-reise-backend-wagtail/issues/74
